### PR TITLE
chore: Update title and some fixes in README.md

### PR DESCRIPTION
**Pull request by AlbionaHoti**
# What :computer: 
* updated zkSync to ZKsync
* some mini fixes in the copy

### CODE REVIEW

**Review by jennyg0 — COMMENTED** [review]
still zkSync on lines 163, 286, 288

**Comment by AnastasiiaVashchuk** [comment]
please update `zkSync` to `ZKsync` in other places as well:
image

**Comment by AnastasiiaVashchuk** [comment]
to the comment above:
image

**Comment by AnastasiiaVashchuk** [comment]
@AlbionaHoti

**Comment by dutterbutter** [comment]
Closing due to staleness.

**Pull request closed without merging**
