### PR TITLE
fix: update typo in link to dev discussion

### PR DESCRIPTION
**Pull request by krauspt**
# What :computer: 
- I've found typo in link to developer discussion, this PR fixes the link. Maybe the target [repo](https://github.com/zkSync-Community-Hub/zkync-developers/discussions) should be renamed, because the original typo is in the repository name.

# Why :hand:
- To keep external resources approachable.

# Evidence :camera:
No special evidence.

### CODE REVIEW

**Comment by krauspt** [comment]
@MexicanAce is there anything from my side that needs to be done?

**Comment by MexicanAce** [comment]
@krauspt Thanks for the ping (apologies, this got lost in my GitHub feed) and thank you for finding this!! Also just realized that the GitHub Discussions repo has a typo in it 🤦 

I've kicked off the builds and will approve/merge here soon

**Review by MexicanAce — APPROVED** [review]
LGTM

**Comment by MexicanAce** [comment]
We'll look into fixing the typo in the upstream repo, but that will require more changes as URL redirects are not supported by GitHub for repo renaming.

**Pull request merged**
